import type { Metadata } from "next";
import "./globals.css";
import LeftSidebar from "../components/LeftSidebar";
import TopNavbar from "../components/TopNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex h-screen font-sans`}
      >
        <LeftSidebar />

        {/* Main Content Area */}
        <div className="flex-1 flex flex-col">
          <TopNavbar />
          <main className="flex-1 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
